import React from 'react'
import type { Metadata } from 'next'
// import Link from 'next/link'
import localFont from 'next/font/local'
import Nav from '@/components/nav'
import './globals.css'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
  auth: React.ReactNode
}

export default function RootLayout(props: Props) {
  const { auth, children } = props

  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
    >
    <header className="w-[600px] mx-auto text-center mt-8">
      <nav className="flex justify-center gap-8">
        <Nav />
      </nav>
    </header>
    <div className="w-[600px] mx-auto p-8 border border-gray-200 rounded-xl bg-white my-8">
      {children}
      {auth}
    </div>
    </body>
    </html>
  )
}
